// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhuLaiThuVienThienApi.Data;

#nullable disable

namespace NhuLaiThuVienThienApi.Migrations
{
    [DbContext(typeof(NhuLaiThuVienThienDbContext))]
    [Migration("20240912094923_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThuVienNhuLaiThien.Domain.Book", b =>
                {
                    b.Property<int>("book_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("book_id"));

                    b.Property<string>("book_author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("book_category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("book_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("book_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("book_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("book_id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("ThuVienNhuLaiThien.Domain.Chapter", b =>
                {
                    b.Property<int>("chapter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chapter_id"));

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.Property<string>("chapter_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chapter_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("chapter_id");

                    b.HasIndex("book_id");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("ThuVienNhuLaiThien.Domain.Chapter", b =>
                {
                    b.HasOne("ThuVienNhuLaiThien.Domain.Book", "book")
                        .WithMany("chapters")
                        .HasForeignKey("book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("book");
                });

            modelBuilder.Entity("ThuVienNhuLaiThien.Domain.Book", b =>
                {
                    b.Navigation("chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
